[package]
name = "verynicetable"
version = "0.6.3"
edition = "2024"
authors = ["Quentin Richert <noreply@richert.co>"]
description = "Number one table."
license = "MIT OR Apache-2.0"
repository = "https://github.com/qrichert/verynicetable.git"
readme = "README.md"
keywords = ["table", "table-formatting", "terminal", "cli-output", "alignment"]
categories = ["command-line-interface", "value-formatting"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }

[dependencies]
